program ::= { statement } exit
statement ::= decl | assign
decl ::= type [ "mut" ] ident "{" expr "}"
assign ::= ident ":=" expr
expr ::= arith [ ( "==" | "!=" ) arith ]
arith ::= term { ( "+" | "-" ) term }
term ::= factor { "*" factor }
factor ::= number | "true" | "false" | ident
exit ::= "exit" factor
type ::= "i32" | "i64" | "bool"
